svc() parameters 
kernel is Kernel coefficient for ‘rbf’, ‘poly’ and ‘sigmoid’
c-Regularization parameter. The strength of the regularization is inversely proportional to C. 

gama is kernal coefficients for rbf,poly
if gamma='scale' (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma
if ‘auto’, uses 1 / n_features
if float, must be non-negative.

In [3]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [4]:
df=pd.read_csv('/content/heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
def fitting(x,y,C,gamma):
   x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
   iters=['rbf','poly','sigmoid']

   for i in iters:
     model=SVC(kernel=i,probability=True,C=C,gamma=gamma)
     clf=model.fit(x_train,y_train)

     pred_train=model.predict(x_train)
     pred_test=model.predict(x_test)

     #use score to get accuracy of model
     #test_score=model.score(x_test,y_test)
     print("accuracy score: ",accuracy_score(y_test,pred_test))
     matrix=metrics.confusion_matrix(y_test,pred_test) 
     print("confusion_matrix \n",matrix)
     print(classification_report(y_test,pred_test,zero_division=0))
     

      #evaluate train model
     train_score=model.score(x_train,y_train)
     print("accuracy score: ",train_score)

     print(classification_report(y_train,pred_train,zero_division=0))

In [6]:
x=df.drop('target',axis=1)
y=df['target'].values
fitting(x,y,1,'scale')

accuracy score:  0.6885245901639344
confusion_matrix
 [[13 14]
 [ 5 29]]
              precision    recall  f1-score   support

           0       0.72      0.48      0.58        27
           1       0.67      0.85      0.75        34

    accuracy                           0.69        61
   macro avg       0.70      0.67      0.67        61
weighted avg       0.70      0.69      0.68        61

accuracy score:  0.6652892561983471
              precision    recall  f1-score   support

           0       0.70      0.47      0.56       111
           1       0.65      0.83      0.73       131

    accuracy                           0.67       242
   macro avg       0.68      0.65      0.65       242
weighted avg       0.67      0.67      0.65       242

accuracy score:  0.7213114754098361
confusion_matrix
 [[15 12]
 [ 5 29]]
              precision    recall  f1-score   support

           0       0.75      0.56      0.64        27
           1       0.71      0.85      0.77        34

    accuracy                           0.72        61
   macro avg       0.73      0.70      0.71        61
weighted avg       0.73      0.72      0.71        61

accuracy score:  0.6776859504132231
              precision    recall  f1-score   support

           0       0.70      0.51      0.59       111
           1       0.66      0.82      0.73       131

    accuracy                           0.68       242
   macro avg       0.68      0.67      0.66       242
weighted avg       0.68      0.68      0.67       242

accuracy score:  0.5573770491803278
confusion_matrix
 [[ 0 27]
 [ 0 34]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        27
           1       0.56      1.00      0.72        34

    accuracy                           0.56        61
   macro avg       0.28      0.50      0.36        61
weighted avg       0.31      0.56      0.40        61

accuracy score:  0.5371900826446281
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       111
           1       0.54      0.99      0.70       131

    accuracy                           0.54       242
   macro avg       0.27      0.50      0.35       242
weighted avg       0.29      0.54      0.38       242

In [7]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [8]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])